### ISSUE TITLE
Print some information on the compilation process

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/contract-deploy-tools#20]
We used to have some information on the compilation process like the used solc version, we should include that again. 

 - Solc version

Should we print that information also on `compile`?

Should we add information on the generated output? Populus had an info like "Wrote output of n contracts to x"

**Comment by berndbohmeier** [comment]
@schmir Something to add? Please go ahead.

**Comment by schmir** [comment]
path to solc binary. not sure what else. I'm also fine with having this info on compile

**Comment by schmir** [comment]
If we add this as `pytest_report_header` to the plugin, it will print this information even when no solidity compilation is involved (e.g. for py-eth-index). It's just noise there.

At this point I would prefer to either not report it or explicitly require the plugin, see the following on how to do that:  https://docs.pytest.org/en/2.8.7/writing_plugins.html#requiring-loading-plugins-in-a-test-module-or-conftest-file

**Comment by berndbohmeier** [comment]
I guess explicitly requiring the plugin is nice to have anyways. I was also thinking to make it a bit configurable, for example that the clean_blockchain fixture can be configured if it is autoused or not. 

For the compile information, can we not just print it from the compilation fixture? Then it would only get printed, if we indeed compiled something.

**Comment by schmir** [comment]
> For the compile information, can we not just print it from the compilation fixture? Then it would only get printed, if we indeed compiled something.

Yes, that would work, but I do think the information may get lost or is at least a bit harder to spot. 

If you don't mind, I would go for making activation of the plugin non-automatic (i.e. removing the pytest11 entry point) and requiring it explicitly via 'pytest_plugins = ...' in our conftest files.

**Comment by berndbohmeier** [comment]
yes, I am fine with this.
But this would still mean that this gets printed for example in the relay server tests even though nothing will get compiled there.

**Comment by berndbohmeier** [comment]
done
