### ISSUE TITLE
Add option to use environment variables for common options

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/contract-deploy-tools#30]
For jsonrpc and keystore for example, see auction tools in the blockchain repo.

**Comment by weilbith** [comment]
As proposal for common options, I would include all except: `--nonce`, `--contract-address`, `--keystore-path` and `--private-key`. All of them are too specific or a single command (execution).
Furthermore I would suggest to use the prefix `DEPLOY_TOOLS_` to identify the variables relation to the tool (similar how used for the auction deploy tool). The longer more specific version would be `CONTRACT_DEPLOY_TOOLS_`, even if this does not correlate with the package name.
Moreover I think we should clean up the code of the auction deploy tool afterwards. Most of the options are copy pasted and extended with the `envvar` parameter only. The only not common option remaining would be `AUCTION_DEPLOY_ADDRESS`.

**Comment by weilbith** [comment]
I used the chance to tidy up the `auction-deploy` tool. Make them much more clean without redundant code.

**Comment by berndbohmeier** [comment]
I can see your reasoning for nonce and contract-address, but keystore path and private key would make sense I think.

**Comment by berndbohmeier** [comment]
Ah, I just saw that you did it for keystore, and  you are right, it does not make sense for privatekey. So I am fine.
